[package]
name = "AdventOfCode2025"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.9"
itertools = "0.14.0"
png = "0.18.0"
z3 = "0.19.6"

[[bin]]
name = "AdventOfCode2025"
path = "main.rs"
